---
- name: Install wget on Ubuntu
  apt:
    name: wget
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Install wget on Amazon Linux
  yum:
    name: wget
    state: present
  when: ansible_distribution == "Amazon"
